[uat-webservers]
172.31.40.106 ansible_ssh_user='ec2-user' ansible_ssh_private_key_file=/home/ec2-user/Tooling.pem
172.31.37.82 ansible_ssh_user='ec2-user' ansible_ssh_private_key_file=/home/ec2-user/Tooling.pem